# Generated by Django 3.1.4 on 2020-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
